### ISSUE TITLE
p-field values are not always copied at initialization of a user-defined opcode

### ISSUE THREAD

**Issue by glocq** [csound/manual#101]
According to [this page of the manual](https://csound.github.io/docs/manual/opcode.html), if a user-defined opcode is used in an instrument, "all p-fields" of the instrument "are automatically copied at initialization" of the opcode.

However, if some p-fields in the score are not _directly_ used by an instrument, they will be ignored (with a warning) - as long as no higher p-field is directly used. So if some p-field is used by a UDO inside an instrument only, it will simply be ignored. I think this is worth mentioning.

Here is an example:

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>


opcode Celesta, a, 0
aenv    transeg     0, 0.007, -4, 1, p3-0.007, -4, 0
asig    oscils      0dbfs, p4, 0
        xout        aenv*asig
endop


instr 1
// The following line is a workaround, uncommenting it allows p4 to be passed to the UDO
// iuseless = p4
asig    Celesta
        outs        asig, asig
endin


</CsInstruments>
<CsScore>
i1 0 2 440
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
I think this is a csound bug

**Comment by glocq** [comment]
I got told the contrary [there](https://github.com/csound/csound/issues/689) though...

**Comment by vlazzarini** [comment]
yes, we need to amend the manual, not the code.

**Comment by vlazzarini** [comment]
It should say "all pfields defined in the calling instrument"

**Comment by kunstmusik** [comment]
This has been the behavior for a very long time.  (I've used the idummy =
px trick in the past as well.)

However, this raises two issues to me:

1. Should this be the behavior?
2. Should UDOs be written that read pfields?

Having written UDOs that use pfields, I'm not sure it was a good idea, and
it might have been better to just pass values to the UDO. Because of this,
I think it's probably better to just document the behavior as-is and also
add a warning recommending against using p-fields within UDOs, with the
exception of p2 and p3.

**Comment by jpffitch** [comment]
If you have decided the manal is wrong can someone change it?  i would if I knew where

**Comment by vlazzarini** [comment]
This page? https://csound.github.io/docs/manual/opcode.html

**Comment by jpffitch** [comment]
Changed but reads oddly to me

<listitem><para>all p-fields (including
         <emphasis>p1</emphasis>) defined in the calling 
instrument</para></listitem>

p fields are not defined in instruments, but referenced

**Comment by vlazzarini** [comment]
you're absolutely right, "all p-fields referenced in the calling instrument" is better. However, I see this is not right either. It's "all p-fields up to and including the highest-numbered one referenced in the calling instrument" or something similar. 

This is because even if we did not reference pN, but referenced p{N+1}, pN is still available to the
opcode.
