### ISSUE TITLE
how to treat FLTK opcodes?

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#422]
are they all functional on all platforms? 
Do they have to be moved over to the Deprecated section?

**Comment by tgrey1** [comment]
Going to close this out, as we discussed in the manual meeting held today.

FLTK opcodes are *NOT* functional on all platforms.
Unfortunately they won't be deprecated until there is a good replacement that's useable on all platforms (recommendations welcome with the core csound team)
We can minimize the prevalence of FLTK in examples, but the FLTK opcodes need to remain and have working examples

Right now, as far as the manual team's effort goes, our steps are:
- find all FLTK examples
- tag the examples
- write replacement non FLTK examples
- move old example.csd to example-FLTK.csd
- wait for deprecation officially in core
- once deprecated by core team, examples to delete are now easily identified by filename :)

**Comment by csounder** [comment]
an excellent plan.
- what is most important is to replace the examples that are not actually
showing an FLTK opcode but use an FLTK opcode.
- I did find a way some time ago to get the FLTK opcodes to work again on
the Mac and with Catalina, but I have since forgotten what the combination
of things was to make them work.

your proposal is excellent.

-dB

*Dr. Richard Boulanger*
