### ISSUE TITLE
scanu incomplete

### ISSUE THREAD

**Issue by jpffitch** [csound/manual#533]
Second argument irate is not explained

**Comment by AsterixMusic** [comment]
I think is the rate speed in seconds of the "force" applied by the performer.
According to Risset should be about 15 Hz.
I tried 0.1 - 0.5 - 1 and you can see the spectral changes.
...I have to understand deeply to explain better...

```csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o scans.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

    sr =   44100
    ksmps =   128
    nchnls =   1

    instr 1
a0  = 0
;   scanu init, irate, ifnvel, ifnmass, ifnstif, ifncentr, ifndamp, kmass, kstif, kcentr, kdamp, ileft, iright, kpos, kstrngth, ain, idisp, id
    scanu 1,     p6,    6,       2,       3,     4,        5,       2,     .1,    .1,     -.01,  .1,    .5,     0,    0,        a0,  1,     2
;ar scans kamp,      kfreq,      ifntraj, id
a1  scans ampdb(p4), cpspch(p5), 7,       2
    out a1
    endin


</CsInstruments>
<CsScore>

; Initial condition
f1 0 128 7 0 64 1 64 0
   
; Masses
f2 0 128 -7 1 128 1
   
; Spring matrices
f3 0 16384 -23 "string-128.matrix"
   
; Centering force
f4  0 128 -7 0 128 2
   
; Damping
f5 0 128 -7 1 128 1
   
; Initial velocity
f6 0 128 -7 0 128 0
   
; Trajectories
f7 0 128 -5 .001 128 128

; Note list
i1 0  7  86 6.00 0.1
;i1 0  7  86 6.00 0.5
;i1 0  7  86 6.00 1


e


</CsScore>
</CsoundSynthesizer>


```
<img width="1327" alt="Screenshot 2021-04-25 at 10 39 34" src="https://user-images.githubusercontent.com/68651266/115987145-0fa37900-a5b4-11eb-81a1-41a6d01c8dad.png">

**Comment by tjingboem** [comment]
i found in http://www.csounds.com/scanned/toot/index.html
this about scanu irate:

irate: The amount of time between successive updates of the mass state. Kind of like the sample period of the system. If the number is big, the string will update at a slow rate showing little timbral variability; otherwise it will change rapidly resulting in a more dynamic sound.

And i now think scanu should get its own example where this irate has different settings, indeed ranging from 0 - 1ish, from slow to fast

Score:
i1 0  3  86 6.00 0.001      ; fast updates
i1 5  7  86 6.00 0.005       ; slower
i1 15  10  86 6.00 0.1     ; ..and updating much slower

**Comment by tjingboem** [comment]
i'll close this one and add a new one for the example using different rates

**Comment by csounder** [comment]
Yes,  it turns out that this is a sonically significant parameter.
When I teach scanned, I always start by playing with this in class.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
