### ISSUE TITLE
re-examine all Scanned Synthesis examples

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#535]
- implement DC blocker

**Comment by csounder** [comment]
Good.  Actually it is nice to add a low pass shelving filter too (cut off around 8k) as scanned surfaces tend to evolve to high frequencies - this mellows things a bit

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
there are a bunch of Scanned opcodes, we can implement a low pass filter for some of them as a second example, it would do the sound a lot of good.

(Secretly i am hoping that John is able to do an upgrade of the scanned opcodes so that they sound less distorted (irate??). It would be great to have an extra switch in the opcodes to turn off or on to switch between the classic, more distorted sound and the upgraded, more smoothed sound...that would be nice to hear as a first example as well)

**Comment by csounder** [comment]
I am hoping for this too!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
matrices with bigger tables?

**Comment by AsterixMusic** [comment]
Experimenting...
It seems tables are not limited to 128 * 128 = 16384 points.
I tried with a 256 * 256 = 65536 and it seems to work...
The optional [iorder] parameter in "scans" is the interpolation, using cubic interpolation seems reduce the "distortion".
[string-256.txt](https://github.com/csound/manual/files/6382896/string-256.txt)


```csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o scans.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

    sr =   44100
    ksmps =   128
    nchnls =   1

    instr 1
a0  = 0
;   scanu init, irate, ifnvel, ifnmass, ifnstif, ifncentr, ifndamp, kmass, kstif, kcentr, kdamp, ileft, iright, kpos, kstrngth, ain, idisp, id
    scanu 1,     p6,    6,       2,       3,     4,        5,       2,     .1,    .1,     -.01,  .1,    .5,     0,    0,        a0,  1,     2
;ar scans kamp,      kfreq,      ifntraj, id, cubic interpolation
a1  scans ampdb(p4), cpspch(p5), 7,       2,   3
a1 dcblock a1

    out a1*0.5
    endin


</CsInstruments>
<CsScore>

; Initial condition
f1 0 128 7 0 64 1 64 0
   
; Masses
f2 0 128 -7 1 128 1
   
; Spring matrices
;f3 0 16384 -23 "string-128.matrix"

f3 0 65536 -23 "string-256.txt"
   
; Centering force
f4  0 128 -7 0 128 2
   
; Damping
f5 0 128 -7 1 128 1
   
; Initial velocity
f6 0 128 -7 0 128 0
   
; Trajectories
f7 0 128 -5 .001 128 128

; Note list
i1 0   7  86 6.00 0.03 


e


</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
Yes, you are right, i didn't notice the cubic interpolation option-

Now that Stefano has proven that it is possible to use bigger matrices, i must conclude i understand even less on how to look at Scanned...

**Comment by tjingboem** [comment]
And the values of the table do not have to be to the power of 2.
Probably this is faster to compute, but nowadays that does not seem to be a problem anymore

Same instr as above, other score

```
</CsInstruments>
<CsScore>

; Initial condition
f1 0 120 10 1
   
; Masses
f2 0 120 -7 1 128 1
   
; Spring matrices
;f3 0 16384 -23 "string-128.matrix"

f3 0 65536 -23 "/media/menno/datae/onderzoek/manualExamples/string-256"
   
; Centering force
f4  0 120 -7 0 128 2
   
; Damping
f5 0 120 -7 1 128 1
   
; Initial velocity
f6 0 120 -7 0 128 0
   
; Trajectories
f7 0 120 -5 .001 128 128

; Note list
i1 0   7  86 6.00 0.03 


e


</CsScore>
</CsoundSynthesizer>
```

but changing the tables to 130 instead of 128, the instr runs for a moment but then blows up...
i would say the table beibg 256*256 would be more than enough, but here my lack of understanding enters the room...

```
</CsInstruments>
<CsScore>

; Initial condition
f1 0 130 10 1
   
; Masses
f2 0 130 -7 1 128 1
   
; Spring matrices
;f3 0 16384 -23 "string-128.matrix"

f3 0 65536 -23 "/media/menno/datae/onderzoek/manualExamples/string-256"
   
; Centering force
f4  0 130 -7 0 128 2
   
; Damping
f5 0 130 -7 1 128 1
   
; Initial velocity
f6 0 130 -7 0 128 0
   
; Trajectories
f7 0 130 -5 .001 128 128

; Note list
i1 0   7  86 6.00 0.03 


e


</CsScore>
</CsoundSynthesizer>
```

**Comment by AsterixMusic** [comment]
I see now my example is wrong, I put a 256 point matrix, but I'm scanning only 128.
Have to look further...

**Comment by tjingboem** [comment]
ToDo list for (x)scan opcodes

1. i've seen in scanu and scanu2 words like ifndisplace and ifnmatrix etc. Do the same for xscanu
2. xscansmap needs an example: no xscansmap example #233
3. scanhammer needs an example: no scanhammer example #307
4. "The matrix file “string-128.matrix”, as well as several other matrices, is also available in a zipped file from the Scanned Synthesis page at cSounds.com." is no longer true as matrix files have been renamed
5. what are the differences between scan and xscan opcodes??
6. re check all examples and extend their options
7. add --limiter=0.9 for protection
8. perhaps images of the used trajectories and matrices as used in the example- but that can take a lot of space on the manual page. It could be something as you see on the manual page for GEN18 https://csound.com/manual/GEN18.html
9. maybe i am not seeing this correctly, but would it be possible to have an image of the matrix (linseg or otherwise) and superimpose the trajectory in red, like an arrow pointing the start and end of this trajectory?? not sure
10. explain briefly the differences Binair and Text matrices on https://csound.com/manual/SiggenScanTop.html

**Comment by csounder** [comment]
Yes it would be good for John to explain the difference in scan and xscan but for sure they should now have the same parameter names.

And yes John could explain the difference between binary and text forms

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
I should change the info at cSounds.com for sure.  John can tell you the
difference between the sc

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

On Jun 6, 2021, at 3:34 PM, Menno Knevel ***@***.***> wrote:

﻿

ToDo list for (x)scan opcodes

   1. i've seen in scanu and scanu2 words like ifndisplace and ifnmatrix
   etc. Do the same for xscanu
   2. xscansmap needs an example: no xscansmap example #233
   <https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Nzb3VuZC9tYW51YWwvaXNzdWVzLzIzMw==&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=TjMrMEJwN29UT1JTM1dPNThlbWoyRjNQRmFGd01tUGV4b1ZmSzBaZXZRcz0=&h=18b9a3a77d10468abb7778f5c026c5d4>
   3. scanhammer needs an example: no scanhammer example #307
   <https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Nzb3VuZC9tYW51YWwvaXNzdWVzLzMwNw==&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=ZGhQUml2NXlla3kzYm9sa2ZjMGVkZ05VYWdJbmRFcTRlS2lPRlBKZ00rQT0=&h=18b9a3a77d10468abb7778f5c026c5d4>
   4. "The matrix file “string-128.matrix”, as well as several other
   matrices, is also available in a zipped file from the Scanned Synthesis
   page at cSounds.com." is no longer true as matrix files have been renamed
   5. what are the differences between scan and xscan opcodes??
   6. re check all examples and extend their options
   7. add --limiter=0.9 for protection
   8. perhaps images of the used trajectories and matrices as used in the
   example- but that can take a lot of space on the manual page. It could be
   something as you see on the manual page for GEN18
   https://csound.com/manual/GEN18.html
   <https://us-west-2.protection.sophos.com?d=csound.com&u=aHR0cHM6Ly9jc291bmQuY29tL21hbnVhbC9HRU4xOC5odG1s&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=eTU0QVdUOTY5RVpYM2V6ZC9xdTZkZ1dhTFBUb3d2bmYvU1dkSTExcEhuOD0=&h=18b9a3a77d10468abb7778f5c026c5d4>
   9. maybe i am not seeing this correctly, but would it be possible to
   have an image of the matrix (linseg or otherwise) and superimpose the
   trajectory in red, like an arrow pointing the start and end of this
   trajectory?? not sure
   10. explain briefly the differences Binair and Text matrices on
   https://csound.com/manual/SiggenScanTop.html
   <https://us-west-2.protection.sophos.com?d=csound.com&u=aHR0cHM6Ly9jc291bmQuY29tL21hbnVhbC9TaWdnZW5TY2FuVG9wLmh0bWw=&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=bEoxTGhFckJJYlFzd1ZSNVR3REJuWUFyRXIzTzdEeXFpODNSMERJdTU2RT0=&h=18b9a3a77d10468abb7778f5c026c5d4>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Nzb3VuZC9tYW51YWwvaXNzdWVzLzUzNSNpc3N1ZWNvbW1lbnQtODU1NDUwNjU1&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=Ui9zdXJFUUsvRWpyczNmWCsrVEVtOStrZmdCZ2h4aWdneWxsUnJpZ2szRT0=&h=18b9a3a77d10468abb7778f5c026c5d4>,
or unsubscribe
<https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BQUxXWUZSWk5EQ0I0UkJQVU9OSkhXRFRSUEVVUEFOQ05GU000M1NLSVNFQQ==&i=NWYxNzBkMDNiNTVmZGEwZmIyNjczYmRm&t=TWNqOFFiaEVuckp6Q3ZBRkszWDF0aHBwazM3bVE4Qlo1ckVnVVlkMnhLYz0=&h=18b9a3a77d10468abb7778f5c026c5d4>
.

**Comment by tjingboem** [comment]
scan and xscan now have the same parameter names.

**Comment by csounder** [comment]
excellent!  Max Mathews' was always imagining this as a model of his
'radio-baton' receiver surface (the size and shape of a large pizza-box)
that he could displace with one or both of his 'radio-baton' transmitter
sticks.  The 'hammer' idea comes from the fact that you 'wack' with the
sticks to register beats, but in this case he was visualing the 3D evolving
timbre-wave, above the surface that he was deforming, or displacing (at the
start of a note, with the sticks (which have colored sponge balls around
the heads (nerf balls) to stop from making noise if one accidentally
'struck the surface' were now, in his imagination, in the shape of some 3D
object that would deform the waveform in a pattern or in the form of a
sineWave.

Now, I believe that John has added the option (which one could have done
with a gen routine) that there is a default that initializes the surface
with noise and into a random state of peaks and valleys at the start and
then it evolves according to the other parameters - this too was one of Max
Mathews' original ideas for the model/system

-dB


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
also check new example for scanu #534

**Comment by csounder** [comment]
You might want to consider adding a link for 'all' used files in the scan
examples - (and even in some other examples)
- when the paths are right, there is no issue, click on the .csd and things
run, but

You say this:
Examples

Here is an example of the scanu opcode. It uses the files
*scanu-musical.csd* <https://csound.com/manual/examples/scanu-musical.csd>
 and *MIDIpad.mid* <https://csound.com/manual/examples/MIDIpad.mid>.

Yet this example also uses (and requires) the file: 'string-128.matrxB' to
render correctly

It was nice to be able to go to your latest manual (
https://csound.com/manual/), click on and download these two links and
'almost' run the .csd, but to run the .csd,

I had to go to the latest github manual examples folder to locate the
.matrix file.


Once you do that - it sounds quite lovely.  And THANKS for including this
important and beautiful example by Shengzheng Zhang

- could you also add the following to the .csd

; by Shengzheng Zhang (aka John Towse)



*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
Note also that with some 'updating of comments and names' that this example
does show clearly the effect of the rate parameter on the scanu opcode and
you might want to consider using it for scanu as well.

<CsoundSynthesizer>

<CsOptions>

; Select audio/midi flags here according to platform

; Audio out Audio in No messages

-odac -d ;;;RT audio I/O and don't display waves

; For Non-realtime ouput leave only the line below:

; -o scanu.wav -W ;;; for file output any platform

</CsOptions>

<CsInstruments>


sr = 44100

ksmps = 32

nchnls = 2

0dbfs = 1


instr 1


a0 = 0 ; no external input

; scanu init, irate, ifnvel, ifnmass, ifnstif, ifncentr, ifndamp, kmass,
kstif, kcentr, kdamp, ileft, iright, kpos, kstrngth, ain, idisp, id

scanu 1, p6, 6, 2, 3, 4, 5, 2, .1, .1, -.02, .1, .5, 0, 0, a0, 1, 2

;ar scans kamp, kfreq, ifntraj, id

a1 scans ampdb(p4), cpspch(p5), 7, 2

a1 *= 0.00006 ; lower amplitude &

a1 dcblock2 a1 ; remove DC offset

outs a1, a1

endin


</CsInstruments>

<CsScore>

f1 0 128 7 0 64 1 64 0 ; Initial condition

f2 0 128 -7 1 128 1 ; Masses

f3 0 16384 -23 "string-128.matrix" ; Spring matrices

f4 0 128 -7 0 128 2 ; Centering force

f5 0 128 -7 1 128 1 ; Damping

f6 0 128 -7 0 128 0 ; Initial velocity

f7 0 128 -5 .001 128 128 ; Trajectories



i1 0 3 86 6.00 0.001 ; fast updates of the mass state

i1 5 7 86 6.00 0.005 ; slower updating...

i1 15 10 86 6.00 0.1 ; ..and updating much slower still


e

</CsScore>

</CsoundSynthesizer>


*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
scanu will get (2?) other examples.
The example of Shengzheng Zhang is a scanu-musical example, so part of the musical examples group. 
Basic example(s) will be added.

**Comment by tjingboem** [comment]
see no xscansmap example #233

**Comment by tjingboem** [comment]
- [ ] matrices with bigger tables
- [ ]

**Comment by tjingboem** [comment]
all relevant information here is consumed and taken into account into the newer issue improve and extend all Scanned Synthesis examples #757

**Comment by csounder** [comment]
Absolutely fantastic.  What a major clarification, contribution, inspiration.Dr. Richard BoulangerProfessorElectronic Production and DesignBerklee College of MusicOn Sep 13, 2024, at 6:44 AM, Menno Knevel ***@***.***> wrote:﻿
all relevant information here is consumed and taken into account into the newer issue improve and extend all Scanned Synthesis examples #757
