### ISSUE TITLE
Could someone review my PR from August 2020?

### ISSUE THREAD

**Issue by bhagerty** [csound/manual#621]
I made a pull request in August 2020 to make what I thought were pretty non-controversial improvements to the page about building the manual. Any chance someone could review it and, ideally, merge it? There are a lot of open issues, but currently it's the only open pull request that I can see.

**Comment by kunstmusik** [comment]
@tjingboem @fggp Is this something that can be processed easily?

**Comment by tjingboem** [comment]
I've read the text but, unfortunately am not an expert on the subject, but it all seems correct to me.
I would feel better if @fggp could take a look, just to be sure.

Regarding the "Note: if you are on Ubuntu, the `Makefile` will _not_ work, because it calls Python with `python` and not `python3`. You will need to edit the Makefile so that you call `python3` (the executable name for Python on Ubuntu)."
i have a program installed 'python-is-python3' . This little program: "This is a convenience package which ships a symlink to point the /usr/bin/python interpreter at the current default python3" 
Perhaps this can be added.

**Comment by bhagerty** [comment]
@tjingboem I would be happy to make a note about `python-is-python3`. Should I change the original PR or make a separate change? I'm not an expert in the process for stacking up changes.

**Comment by bhagerty** [comment]
@tjingboem makes sense. So I would propose replacing the lines about using Ubuntu with the following:

Note: if you are on Ubuntu, the `Makefile` will probably _not_ work, because it calls Python with `python` and not `python3`. You will need to either (1) edit the Makefile so that you call `python3` (the executable name for Python on Ubuntu) or (2) install something like [`python-is-python3`](https://packages.debian.org/sid/main/python-is-python3), a convenience package for Debian and Ubuntu that creates a symlink from `python` to `python3`.

**Comment by bhagerty** [comment]
@tjingboem I'm closing this now that the PR is merged, but could you make the additional PR? Thanks!

**Comment by tjingboem** [comment]
the additional PR is done.
Thanks for your work!
